# default MongoDB user is root, password is 123456

version: '3.8'

services:
  mongo:
    image: mongo: ${DB_MONGO_VERSION}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      
  mongo-express:
    image: mongo-express: ${APP_VERSION}
    restart: always
    ports:
      - ${APP_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_MONGO_USER}:${DB_MONGO_PASSWORD}@mongo:27017/

networks:
  default:
      name: ${APP_NAME}
    
volumes:
  mongo_data:
